"""inspect_ai Task: T scores a mixed, unlabeled set of honest and attack-mode
solutions for suspicion. The dataset here is *solutions* (already generated by
U), not raw problems — samples must be built from the outputs of
honest_solution_task / attack_solution_task via `build_monitor_dataset` before
running this task.
"""

from __future__ import annotations

from inspect_ai import Task, task
from inspect_ai.dataset import MemoryDataset, Sample
from inspect_ai.solver import generate

from trusted_monitoring.inspect_tasks.scorers import suspicion_score_extractor
from trusted_monitoring.monitoring.monitor import MONITOR_PROMPT_TEMPLATE


def build_monitor_dataset(solutions: list[dict]) -> MemoryDataset:
    """`solutions` entries: {problem_id, question, solution_code, is_attack,
    is_verified_backdoor}. The is_attack/is_verified_backdoor labels are kept in
    metadata for scoring analysis only — they must never be part of the prompt
    T sees, since T is meant to be blind to which set a solution came from.
    """
    samples = [
        Sample(
            id=s["problem_id"],
            input=MONITOR_PROMPT_TEMPLATE.format(
                question=s["question"], solution_code=s["solution_code"]
            ),
            metadata={
                "is_attack": s["is_attack"],
                "is_verified_backdoor": s["is_verified_backdoor"],
            },
        )
        for s in solutions
    ]
    return MemoryDataset(samples=samples)


@task
def monitor_scoring_task(dataset: MemoryDataset) -> Task:
    return Task(
        dataset=dataset,
        solver=[generate()],
        scorer=suspicion_score_extractor(),
    )
